.gitignore, src/main/java/common/controller/FrontController.java, src/main/webapp/WEB-INF/web.xml
1. datasource 설정 추가
2. Constants 경로 수정
=> feat : datasource 설정 추가

src/main/java/common/controller/AbstractController.java, src/main/java/common/controller/ErrorController.java, src/main/java/common/controller/FrontController.java, src/main/java/util/security/AES256.java, src/main/java/util/security/Sha256.java, src/main/webapp/WEB-INF/message.jsp
1. 단방향, 양방향 암호화 클래스 추가
2. 예외 처리를 위한 메시지 알림 기능 추가
=> feat : 암호화 기능, 에러페이지 처리 추가

src/main/java/board/controller/RegisterController.java, src/main/java/board/model/BoardDAO.java, src/main/java/board/model/BoardDAO_imple.java, src/main/webapp/WEB-INF/board/list.jsp, src/main/webapp/WEB-INF/board/register.jsp, src/main/webapp/WEB-INF/message.jsp, src/main/webapp/css/board/list.css, src/main/webapp/css/board/register.css, src/main/webapp/js/board/list.js, src/main/webapp/js/board/register.js
1. Q&A 게시판 등록기능 추가
2. Q&A 게시판 리스트 순번 수정(rwo_num 사용)
=> feat: 게시판 등록기능 추가

src/main/java/admin/controller/LoginController.java, src/main/java/admin/controller/LogoutController.java, src/main/java/admin/controller/MainController.java, src/main/java/admin/domain/AdminDTO.java, src/main/java/admin/model/AdminDAO.java, src/main/java/admin/model/AdminDAO_imple.java, src/main/java/common/controller/AbstractController.java, src/main/java/common/controller/FrontController.java, src/main/java/common/controller/MainController.java, src/main/webapp/WEB-INF/admin/admin_main.js, src/main/webapp/WEB-INF/admin/admin_main.jsp, src/main/webapp/WEB-INF/admin/login.jsp, src/main/webapp/css/admin/admin.css, src/main/webapp/css/admin/admin_main.css, src/main/webapp/js/admin/admin_main.js
1. 관리자 세션 로그인/로그아웃 기능추가
2. 관리자 메인 페이지 기능 추가
=> feat : 관리자 로그인, 로그아웃, 메인 페이지 추가

src/main/java/login/controller/Login.java, src/main/java/member/controller/RegisterController.java, src/main/java/member/domain/MemberDTO.java, src/main/java/member/model/MemberDAO.java, src/main/java/member/model/MemberDAO_imple.java, src/main/webapp/WEB-INF/header.jsp, src/main/webapp/WEB-INF/login/login.jsp, src/main/webapp/WEB-INF/main.jsp, src/main/webapp/WEB-INF/member/register.jsp, src/main/webapp/js/login/login.js
=> feat : 로그인 기능 추가

src/main/java/board/controller/ListController.java, src/main/webapp/WEB-INF/board/detail.jsp, src/main/webapp/WEB-INF/board/list.jsp, src/main/webapp/WEB-INF/board/register.jsp, src/main/webapp/css/board/detail.css, src/main/webapp/css/board/list.css, src/main/webapp/css/board/register.css
1. Q&A 게시판 헤더 추가
2. Q&A 게시판 css 수정
=> style : Q&A 게시판 헤더 추가 및 css 수정

src/main/java/board/controller/DetailController.java, src/main/java/board/controller/ListController.java, src/main/java/board/controller/RegisterController.java, src/main/java/board/model/BoardDAO.java, src/main/java/board/model/BoardDAO_imple.java, src/main/webapp/WEB-INF/board/list.jsp, src/main/webapp/WEB-INF/board/register.jsp, src/main/webapp/css/board/list.css, src/main/webapp/js/board/list.js
=> feat : Q&A 게시판 세션처리 추가

src/main/java/product/controller/DetailController.java, src/main/webapp/WEB-INF/board/list.jsp, src/main/webapp/WEB-INF/product/detail.jsp, src/main/webapp/css/board/list.css, src/main/webapp/css/product/detail.css, src/main/webapp/images/logo/go_first.svg, src/main/webapp/images/logo/go_last.svg, src/main/webapp/images/logo/next.svg, src/main/webapp/images/logo/prev.svg, src/main/webapp/js/board/list.js, src/main/webapp/js/product/detail.js
1. 상품상세 틀 추가
2. Q&A 게시판 디자인 수정
3. Q&A 게시판 페이징 처리 추가 및 페이징바 디자인 수정
=> feat: 상품 상세 틀 추가

src/main/java/product/controller/DetailController.java, src/main/java/product/model/ProductDAO.java, src/main/java/product/model/ProductDAO_imple.java, src/main/webapp/WEB-INF/product/detail.jsp, src/main/webapp/css/product/detail.css, src/main/webapp/js/product/detail.js
=> feat: 상품상세페이지 추천상품 기능 추가

src/main/java/admin/controller/product/ProductRegisterController.java, src/main/java/admin/controller/product/ProductUpdateController.java, src/main/java/common/controller/AbstractController.java, src/main/webapp/WEB-INF/admin/product/product_register.jsp, src/main/webapp/WEB-INF/admin/product/product_update.jsp, src/main/webapp/WEB-INF/image_carousel_register.jsp, src/main/webapp/WEB-INF/image_carousel_update.jsp
1. 관리자 상품등록/수정 요청 시 AJAX로 변경
2. 이미지 파일 여러번 추가가 가능하도록 기능 수정
=> 관리자 상품등록/수정 기능 수정

src/main/java/member/model/MemberDAO.java
=> fix : 병합 충돌 해결

.classpath, src/main/java/login/controller/Login.java, src/main/webapp/WEB-INF/admin/admin_main.jsp
=> feat : 회원 로그인 휴면 확인 기능 추가

src/main/java/board/model/BoardDAO_imple.java, src/main/webapp/WEB-INF/board/list.jsp, src/main/webapp/WEB-INF/product/detail.jsp, src/main/webapp/css/board/list.css
1. 게시판 리스트페이지 스타일 수정
2. 게시판 상세에서 url 로 이동 예외처리
3. 추천 상품 리스트 짝수개로 고정
=> style: 게시판 리스트페이지 디자인 수정

src/main/java/login/controller/Login.java, src/main/java/member/controller/MemberDeactivate.java, src/main/java/member/model/MemberDAO_imple.java, src/main/webapp/WEB-INF/member/memberDeactivate.jsp, src/main/webapp/css/member/MemberDeactivate.css
=> feat: 휴면 해제 기능 추가

src/main/webapp/WEB-INF/member/memberDeactivate.jsp, src/main/webapp/css/member/MemberDeactivate.css
=> style: 휴면 해제페이지 디자인수정

src/main/java/member/controller/FindUpdatePwdController.java, src/main/java/member/controller/FindUpdatePwdEndController.java, src/main/java/member/controller/MobileDuplicateCheckController.java, src/main/java/member/controller/PwdCheckController.java, src/main/java/member/model/MemberDAO.java, src/main/java/member/model/MemberDAO_imple.java, src/main/webapp/WEB-INF/login/findPwd.jsp, src/main/webapp/WEB-INF/member/memberDetail.jsp, src/main/webapp/WEB-INF/member/updateFindPwd.jsp, src/main/webapp/js/login/findPwd.js, src/main/webapp/js/member/register.js, src/main/webapp/js/member/updateFindPwd.js, src/main/webapp/js/member/updateMobile.js, src/main/webapp/js/member/updatePwd.js
1. 비밀번호 찾기시 문자인증 기능 추가
2. 문자인증 후 비밀번호 변경
3. 유효성 검사 완료
=> feat: 비밀번호 찾기시 문자인증 기능 추가 비밀번호 변경

src/main/java/product/controller/ProductListController.java, src/main/java/product/controller/SearchList.java, src/main/java/product/model/ProductDAO.java, src/main/java/product/model/ProductDAO_imple.java, src/main/webapp/WEB-INF/category/hamburger_category.jsp, src/main/webapp/WEB-INF/product/category_list.jsp, src/main/webapp/WEB-INF/product/search.jsp, src/main/webapp/WEB-INF/product/search_list.jsp, src/main/webapp/css/category/category_list.css, src/main/webapp/css/category/search.css, src/main/webapp/css/category/search_list.css, src/main/webapp/css/header/hamburger.css, src/main/webapp/js/category/category_list.js
카테고리 리스트 CSS
카테고리 리스트 버튼 DB 연결
서치 페이지 버튼 DB 연결
서치 페이지 캐러셀
햄버거 카테고리  수정
=> 카테고리 리스트 수정

src/main/webapp/WEB-INF/board/detail.jsp, src/main/webapp/WEB-INF/board/list.jsp, src/main/webapp/WEB-INF/product/detail.jsp, src/main/webapp/css/board/list.css, src/main/webapp/css/product/detail.css
1. 게시판 리스트 페이지 디자인 수정
2. 게시판 상세 페이지 디자인 수정
3. 상품 상세 페이지 디자인 수정
=> style: 게시판 디자인 수정

src/main/java/admin/controller/product/ImageDeleteController.java, src/main/java/board/model/BoardDAO_imple.java, src/main/java/member/model/MemberDAO_imple.java, src/main/java/orders/model/OrderDAO_imple.java, src/main/java/product/model/ProductDAO.java, src/main/java/product/model/ProductDAO_imple.java, src/main/webapp/WEB-INF/admin/admin_main.jsp, src/main/webapp/WEB-INF/admin/board/board_detail.jsp, src/main/webapp/WEB-INF/admin/member/member_login_history.jsp, src/main/webapp/WEB-INF/admin/member/member_manage.jsp, src/main/webapp/WEB-INF/admin/order/order_detail.jsp, src/main/webapp/WEB-INF/admin/product/product_detail.jsp, src/main/webapp/WEB-INF/admin/product/product_manage.jsp, src/main/webapp/WEB-INF/admin/product/product_register.jsp, src/main/webapp/WEB-INF/admin/product/product_update.jsp, src/main/webapp/WEB-INF/image_carousel.jsp, src/main/webapp/WEB-INF/image_carousel_update.jsp, src/main/webapp/js/mypage/address.js
1. 상품 이미지 삭제 후 수정 날짜 변경 쿼리 수정
2. 조회 리스트 정렬 문제 수정
=> fix : 상품 이미지 삭제, 조회 리스트 정렬 버그 수정

src/main/webapp/WEB-INF/admin/admin_main.jsp, src/main/webapp/WEB-INF/admin/side_navigation.jsp
1. 로그아웃 수정
2. 관리자 메인 테이블 이동 기능 추가
=> feat : 로그아웃 수정, 관리자 메인 페이지 수정

src/main/webapp/WEB-INF/product/category_list.jsp, src/main/webapp/WEB-INF/product/search.jsp, src/main/webapp/WEB-INF/product/search_list.jsp, src/main/webapp/css/category/category_list.css, src/main/webapp/css/category/search.css, src/main/webapp/css/category/search_list.css
=> 카테고리 리스트 오류 제거

src/main/java/admin/controller/MainController.java, src/main/java/admin/controller/auth/LoginController.java, src/main/java/admin/controller/board/BoardDetailController.java, src/main/java/admin/controller/board/BoardManageController.java, src/main/java/admin/controller/member/MemberDetailController.java, src/main/java/admin/controller/member/MemberLoginHistoryController.java, src/main/java/admin/controller/member/MemberManageController.java, src/main/java/admin/controller/order/OrderDetailController.java, src/main/java/admin/controller/order/OrderManageController.java, src/main/java/admin/controller/product/ImageDeleteController.java, src/main/java/admin/controller/product/ProductDeleteController.java, src/main/java/admin/controller/product/ProductDetailController.java, src/main/java/admin/controller/product/ProductManageController.java, src/main/java/admin/controller/product/ProductRegisterController.java, src/main/java/admin/controller/product/ProductUpdateController.java, src/main/java/board/model/BoardDAO_imple.java, src/main/java/common/controller/AbstractController.java, src/main/webapp/WEB-INF/admin/board/board_detail.jsp, src/main/webapp/WEB-INF/admin/board/board_manage.jsp, src/main/webapp/WEB-INF/admin/member/member_detail.jsp, src/main/webapp/WEB-INF/admin/member/member_login_history.jsp, src/main/webapp/WEB-INF/admin/member/member_manage.jsp, src/main/webapp/WEB-INF/admin/order/order_detail.jsp, src/main/webapp/WEB-INF/admin/order/order_manage.jsp, src/main/webapp/WEB-INF/admin/product/product_detail.jsp, src/main/webapp/WEB-INF/admin/product/product_manage.jsp, src/main/webapp/WEB-INF/admin/product/product_register.jsp
1. 관리자 기능 컨트롤러의 DAO는 생성자에서 초기화하도록 변경
2. 주석 추가
3. JSON 응답을 하는 컨트롤러에서 예외처리 수정
=> refactor : 컨트롤러 생성자 수정
